# Titles and one-line notes for each plate.
#
# Keyed by the same six-character id prefix used by SHADOW_AR in photos.py,
# so reordering a series never detaches a caption from its photograph.
#
#     "prefix": ("Title", "One sentence about the picture."),
#
# A plate with no entry here still builds — it simply shows its number and
# series, exactly as before. Keep titles to a few words and briefs to one
# sentence; the layout is designed around that length.

SHADOW = {
    "852e5a": ("Plumage Unfolded",
               "A greater flamingo turns to preen and the raised wing opens like a fan of coral and white."),
    "459061": ("Standing Curve",
               "The whole body reduced to one line — neck, breast and legs held in a single fall of light."),
    "580dc7": ("Head Beneath the Wing",
               "Folded into its own flank, the bird becomes an anatomy of feathers rather than a face."),
    "f4e43c": ("Study in White",
               "Wing coverts catch what little light there is; the rest of the body is left in the dark."),
    "3dcb05": ("At Rest",
               "A flamingo settles low, red and charcoal feathering running the full width of the frame."),
    "081dbd": ("Written in Light",
               "Only a rim of light survives — the neck drawn as a single stroke against the black."),
    "c54e65": ("Lowered to the Water",
               "The head reaches down to feed, bill inverted, one lit eye holding the centre of the picture."),
    "e59089": ("The Colony",
               "A crowd of necks and bills packed edge to edge, individual birds dissolving into pattern."),
    "cd4b95": ("Among the Resting",
               "One bird stands while the flock sleeps around it, bodies overlapping into a low white drift."),
    "be86f0": ("The Arc",
               "A wing opens to its full span, the leading edge burning orange where the light strikes it."),
    "ab8d4d": ("Distant Company",
               "Seen from far off, a whole flock reduces to a narrow band of pale marks in an empty field."),
    "c24257": ("Plumb Line",
               "Legs, neck and bill fall into one vertical, with no ground offered to stand on."),
    "0a696f": ("The Bow",
               "The body folds forward until the head is very nearly lost in the breast feathers."),
    "daee25": ("Water Thrown",
               "Wings open at the moment of lift, a scatter of droplets caught in the air beneath."),
    "c7688a": ("Coverts",
               "Close in on the wing: red primaries laid over white like tiles on a roof."),
    "92d36c": ("Turned Away",
               "The bird faces into the dark; only the back and the length of one red leg are given to us."),
    "1bbef6": ("Three Lines",
               "Two legs and a neck and almost nothing else — the picture kept to the edge of legibility."),
    "eb3463": ("Gold Water",
               "A single silhouette wades through a surface broken into hundreds of points of light."),
    "beb876": ("The Crown",
               "A stag's antlers emerge from complete darkness while the animal beneath them stays hidden."),
    "ba139c": ("Lowered Head",
               "Antlers swept back and head dropped, the whole weight of the animal implied in shadow."),
    "028ca6": ("The Muzzle",
               "Close enough to read the wet of the nose and the coarse winter coat around the eye."),
    "91ac65": ("Post and Reflection",
               "A cormorant holds a stake above black water ruled by thin bands of reflected light."),
    "13bff6": ("Three Egrets",
               "Necks cross and overlap until it is no longer clear where one bird ends and the next begins."),
    "92fcb0": ("Roost",
               "Egrets stacked on unseen branches, each body a separate white shape hung in the dark."),
    "543aa7": ("Wing Over Stone",
               "An egret preens on a rock, the raised wing catching a narrow shaft of sun."),
    "f42da9": ("Face to Face",
               "A beetle meets the lens head-on, mouthparts and eyes lit against a field of red."),
    "12ad2e": ("Veined Wings",
               "A dragonfly at rest, the venation of the wings reading like drawing on tracing paper."),
    "930f11": ("The Tendril",
               "A damselfly balances on a dry curl of stem: two spirals, one living, one not."),
    "316d19": ("Capped Heron",
               "Cream plumage, a blue bill and one long trailing plume, picked out on a bare branch."),
    "400a7c": ("The Mirror Line",
               "The water surface splits a caiman's head exactly in two, an eye above and an eye below."),
    "5b81af": ("Surfacing",
               "Almost nothing breaks the surface — a snout, an eye, and a thin seam of light on the water."),
    "4a67db": ("Afloat",
               "The whole animal lies at the surface, its ridged back traced in gold from end to end."),
    "61b2da": ("At Close Range",
               "A hunting spider photographed near enough to resolve every hair on the carapace."),
    "301100": ("The Wrapping",
               "A spider stands over silk-bound prey, the web visible only where light snags on it."),
    "e77286": ("Two on a Stem",
               "Two longwing butterflies hang from the same dry stem, wings held open like plates."),
    "350a87": ("Inverted Sky",
               "A heron on the shoreline, photographed so that the reflected sky becomes the ground."),
}

LIGHT = {
    "c1858d": ("Folded In",
               "The bird curls into itself, white on white, with only a bill and one dark eye to anchor it."),
    "d1a879": ("Vermilion",
               "Head tucked away, the picture belongs entirely to the red of the wing coverts."),
    "b89b32": ("Recumbent",
               "A resting body reduced to a long horizontal of white with a seam of colour running through."),
    "9ea739": ("Feather Map",
               "Close enough that the plumage stops being a bird and becomes a landscape of overlapping edges."),
    "9de324": ("Crossed Legs",
               "Balanced on crossed legs in an empty white field, the body made almost weightless."),
    "6ca743": ("Over the Shoulder",
               "The neck reaches back across the body, drawing a loop that closes on itself."),
    "209c30": ("Profile",
               "A head in pure profile: the pink of the bill, the black tip, the pale ring of the eye."),
    "5b39c5": ("Two Necks",
               "One bird faces us and another curves away behind it — a portrait and its own echo."),
    "e10baa": ("Ascending",
               "A line of birds climbs across an otherwise empty frame, black wingtips beating."),
    "339f8d": ("Geometry",
               "Neck, thigh and shin arranged into a set of angles that could have been drafted."),
    "ee5daf": ("On One Leg",
               "The familiar posture stripped of any setting: one leg, one long neck, nothing else."),
    "9b55e5": ("Wet Sand",
               "A faint reflection is the only thing separating the bird from the white ground."),
    "ba1586": ("Drinking",
               "The bill breaks the surface and lifts again, taking a few beads of water with it."),
    "3c7d73": ("Colonnade",
               "A wading group seen at leg height, the limbs standing in for columns."),
    "27cfa3": ("The Meeting",
               "Two necks curve toward one another and, for a moment, close a shape between them."),
    "719e3e": ("Crossing",
               "Two birds pass, their necks crossing at exactly the height of their eyes."),
    "d9c92a": ("The Hook",
               "A single neck bends back on itself until the head hangs level with the breast."),
    "29c0f4": ("Passing Overhead",
               "A small bird crosses an empty sky, given the whole frame in which to be small."),
    "d2c9f3": ("Waterline",
               "Low to the surface, the bird and its reflection meet along a single unbroken line."),
    "d99a87": ("Pelican",
               "A brown pelican in full frame, the long bill running most of the height of the picture."),
    "49e39c": ("The Pouch",
               "Closer still: the hinge of the bill, the loose skin of the pouch, the eye set far forward."),
    "4d8d0a": ("In Breeding Plumage",
               "A great egret in season — the lores turn green and the bill orange, for a matter of weeks."),
    "7a308a": ("Head On",
               "A caiman seen from directly above, symmetrical to the millimetre."),
    "3ffcbd": ("Antlers in Bracken",
               "Fog, dead bracken and two antler tips: the only evidence that a stag is there at all."),
}

MONOCHROME = {
    "99cfbd": ("Crossed Bills",
               "Two pelicans meet, the bills crossing and opening, cut flat into silhouette."),
    "de23d1": ("Bill to Bill",
               "A greeting held long enough to photograph: two heads meeting at the tips."),
    "f0927e": ("The Open Bill",
               "One bird gapes while the other holds still, and the exchange reads as pure shape."),
    "570b5f": ("In Mist",
               "Fog takes the contrast out of everything, leaving the pelicans as grey suggestions."),
    "608160": ("Three on Posts",
               "Three birds on three posts, the middle one pointing its bill straight up."),
    "40b974": ("Braking",
               "Wings thrown wide at the last moment before the feet find the perch."),
    "3fdda2": ("Folded",
               "At rest the bird becomes a single dark mass with one bright edge."),
    "27ca5c": ("Full Span",
               "The whole wingspan opened flat against a blank sky."),
    "ce54af": ("The Line",
               "A row of pelicans with their bills all turned the same way, like a repeated mark."),
    "564393": ("Frigatebirds",
               "Two frigatebirds hold their angular silhouettes without a single wingbeat."),
    "e113e7": ("Raised Bills",
               "Two heads tip back at once, throats stretched, bills pointing to opposite corners."),
    "02194d": ("Sentinel",
               "Upright, still and photographed straight on, the bird takes on a formal quality."),
    "4ae161": ("Turned Head",
               "The head swivels while the body stays square to us: two directions in one animal."),
    "f88b8f": ("Through the Pines",
               "A heron crosses behind pine needles that read as ink laid on white paper."),
    "ee14c1": ("Antlers Against White",
               "Seen from behind, the stag turns its head and the antlers resolve into a bare diagram."),
    "01432a": ("Bare Branch",
               "No animal at all — a single branch, kept for the way it repeats the shape of antlers."),
}
